image: maven:3.9.9-eclipse-temurin-21-alpine
stages:
  - build
  - test
  - package

build-job:
  stage: build
  script:
    - mvn clean package -DskipTests 
  artifacts:
    paths:
      - target/
    expire_in: 1 hour

test-job:
  stage: test
  script: 
    - mvn test
  dependencies:
    - build-job