stages:
  - build-and-test
  - package

build-and-test-job:
  stage: build-and-test
  image: maven:3.9.9-eclipse-temurin-21-alpine
  script:
    - mvn clean verify

package-job:
  stage: package
  image: docker:28
  services:
    - docker:28-dind
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
  only:
    - main
