image: maven:3.9.9-eclipse-temurin-21-alpine
stages:
  - build
  - test
  - package

build-job:
  stage: build
  script:
    - mvn clean package -DskipTests 
  artifacts:
    paths:
      - target/
    expire_in: 1 hour

test-job:
  stage: test
  script: 
    - mvn test
  dependencies:
    - build-job

package-job:
  stage: package
  image: docker:28
  services:
    - docker:28-dind
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
  only:
    - main